### PR TITLE
camnor_noresm_v0.0.4: updates to work with latest oslo_aero code base

### LINKED ISSUE #6: Introduce modifications so that oslo-aero scheme can be used
### What is the feature/what would you like to discuss?

Would like to use oslo-aero as an alternative aerosol scheme in CAM.

### Is there anyone in particular you want to be part of this conversation?

@gold2718 

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Yes

### PR DESCRIPTION
**Pull request by mvertens**
Summary: New OSLO_AERO cpp-ifdefs introduced so that oslo-aero can be turned on as an alternative aerosol scheme

Contributors: @mvertens @gold2718  

Reviewers: @gold2718  

Purpose of changes: #6 introduce modifications so that oslo-aero scheme can be used

Github PR URL: https://github.com/NorESMhub/CAM-Nor-physics/pull/7
Changes made to build system: Need to introduce oslo_aero build

Changes made to the namelist: Need to introrduce oslo_aero namelists

Changes to the defaults for the boundary datasets: new oslo_aero boundary datasets

Substantial timing or memory changes: None

Some `#ifdef OSLO_AERO` and `#ifdef AEROCOM` blocks were introduced to introduce use of the different Oslo Aero interfaces and diagnostic needs.

aux_cam_noresm test suite runs. Baselines fail as expected.

closes #6

### CODE REVIEW

File: physics/cam_diagnostics.F90 [hunk 1]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+      call addfld ('AIRMASSL',(/'lev'/),'A','kg/m2   ','Layer airmass')     
+      call addfld ('BETOTVIS',(/'lev'/),'A','1/km'    ,'Aerosol 3d extinction at 0.442-0.625') ! CAM4-Oslo: 0.35-0.64um
+      call addfld ('BATOTVIS',(/'lev'/),'A','1/km'    ,'Aerosol 3d absorption at 0.442-0.625') ! CAM4-Oslo: 0.35-0.64um
+      call addfld ('BATSW13 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d SW absorption at 3.077-3.846um')
+      call addfld ('BATLW01 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d LW absorption depth at 3.077-3.846um')
+
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Easier to just do:
```suggestion
         write(modeString,"(I2.2)") i
```

File: physics/cam_diagnostics.F90 [hunk 2]
```diff
@@ -197,11 +203,19 @@ subroutine diag_init_dry(pbuf2d)
...
+    use cam_budget,         only: cam_budget_em_snapshot, cam_budget_em_register, thermo_budget_history ! ebudget update
+#ifdef OSLO_AERO
+    use oslo_aero_params,   only: nbmodes 
+#endif
 
     type(physics_buffer_desc), pointer, intent(in) :: pbuf2d(:,:)
 
     integer :: k, m, istage
+
+    integer           :: i          ! OSLO_AERO
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: I'm not thrilled with single letter variables (hard to search for). Any reason we couldn't use `indx` or something similar?

File: physics/cam_diagnostics.F90 [hunk 3]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Camrel"//trim(modeString)
+         if(i.ne.3) call addfld(varName, (/'lev'/),'A','unitless', 'relative added mass for mode'//modeString)
+      enddo  
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Again:
```suggestion
         write(modeString,"(I2.2)") i
```

File: physics/cam_diagnostics.F90 [hunk 4]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+      call addfld ('BETOTVIS',(/'lev'/),'A','1/km'    ,'Aerosol 3d extinction at 0.442-0.625') ! CAM4-Oslo: 0.35-0.64um
+      call addfld ('BATOTVIS',(/'lev'/),'A','1/km'    ,'Aerosol 3d absorption at 0.442-0.625') ! CAM4-Oslo: 0.35-0.64um
+      call addfld ('BATSW13 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d SW absorption at 3.077-3.846um')
+      call addfld ('BATLW01 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d LW absorption depth at 3.077-3.846um')
+
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Camrel"//trim(modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Even better:
```suggestion
         write(varName,'(A,I2.2)') "Camrel", i
```
and skip the modeString stuff entirely

File: physics/cam_diagnostics.F90 [hunk 5]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+         if(i.ne.3) call addfld(varName, (/'lev'/),'A','unitless', 'relative added mass for mode'//modeString)
+      enddo  
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Cxsrel"//trim(modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: again:
```suggestion
         write(varName, '(A,I2.2)') "Cxsrel", i
```

File: physics/cam_diagnostics.F90 [hunk 6]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+      call addfld ('BATOTVIS',(/'lev'/),'A','1/km'    ,'Aerosol 3d absorption at 0.442-0.625') ! CAM4-Oslo: 0.35-0.64um
+      call addfld ('BATSW13 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d SW absorption at 3.077-3.846um')
+      call addfld ('BATLW01 ',(/'lev'/),'A','1/km'    ,'Aerosol 3d LW absorption depth at 3.077-3.846um')
+
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Camrel"//trim(modeString)
+         if(i.ne.3) call addfld(varName, (/'lev'/),'A','unitless', 'relative added mass for mode'//modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Put the `varName` code inside this `if` statement. Why compute it if you are not going to use it?

File: physics/cam_diagnostics.F90 [hunk 7]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+      enddo  
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Cxsrel"//trim(modeString)
+         if(i.ne.3) call addfld(varName, horiz_only, 'A', 'unitless', 'relative exessive added mass column for mode'//modeString)
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Put the `varName` code above inside this `if` statement. Why compute it if you are not going to use it?

File: physics/cam_diagnostics.F90 [hunk 8]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+      call add_default ('NNAT_5  ', 1, ' ')
+      call add_default ('NNAT_6  ', 1, ' ')
+      call add_default ('NNAT_7  ', 1, ' ')
+      call add_default ('NNAT_8  ', 1, ' ')
+      call add_default ('NNAT_9  ', 1, ' ')
+      call add_default ('NNAT_10 ', 1, ' ')
+      call add_default ('NNAT_12 ', 1, ' ')
+      call add_default ('NNAT_14 ', 1, ' ')
+      call add_default ('AIRMASSL', 1, ' ')  !akc6
+      call add_default ('AIRMASS ', 1, ' ')  !akc6
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Does anyone know what those comments are?

File: physics/cam_diagnostics.F90 [hunk 9]
```diff
@@ -365,6 +379,364 @@ subroutine diag_init_dry(pbuf2d)
...
+         varName = "Camrel"//trim(modeString)
+         if(i.ne.3) call add_default(varName, 1, ' ')
+      enddo
+      do i=1,nbmodes
+         modeString="  "
+         write(modeString,"(I2)"),i
+         if(i.lt.10) modeString="0"//adjustl(modeString)
+         varName = "Cxsrel"//trim(modeString)
+         if(i.ne.3) call add_default(varName, 1, ' ')
+      enddo
```
Comment (gold2718) [inline physics/cam_diagnostics.F90]: Putting it all together (example of all previous comments implemented):
```suggestion
      do indx=1,nbmodes
         if(indx /= 3) then
            write(varName, '(A,I2.2)') "Camrel", indx
            call add_default(varName, 1, ' ')
         end if
      end do
      do indx=1,nbmodes
         if(indx /= 3) then
            write(varName, '(A,I2.2)') "Cxsrel", indx
            call add_default(varName, 1, ' ')
         end if
      end do
```

File: physics/physpkg.F90 [hunk 10]
```diff
@@ -1357,7 +1382,11 @@ subroutine tphysac (ztodt,   cam_in,  &
     use waccmx_phys_intr,   only: waccmx_phys_ion_elec_temp_tend ! WACCM-X
     use aoa_tracers,        only: aoa_tracers_timestep_tend
     use physconst,          only: rhoh2o
+#ifdef OSLO_AERO
+    use oslo_aero_model,    only: aero_model_drydep
```
Comment (gold2718) [inline physics/physpkg.F90]: Why isn't `oslo_aero_model` just a shadow file called `aero_model`?

File: physics/physpkg.F90 [hunk 11]
```diff
@@ -1381,7 +1410,11 @@ subroutine tphysac (ztodt,   cam_in,  &
     use lunar_tides,        only: lunar_tides_tend
     use ssatcontrail,       only: ssatcontrail_d0
     use microp_driver,      only: microp_driver_tend
+#ifdef OSLO_AERO
+    use oslo_aero_microp,   only: oslo_aero_microp_run
```
Comment (gold2718) [inline physics/physpkg.F90:1410]: Why isn't oslo_aero_microp just a shadow file called microp_aero?

File: physics/physpkg.F90 [hunk 12]
```diff
@@ -1948,6 +1997,54 @@ subroutine tphysac (ztodt,   cam_in,  &
                   fh2o, surfric, obklen, flx_heat, cmfmc, dlf, det_s, det_ice, net_flx)
        end if
 
+#ifdef AEROCOM
+       !  Estimating hygroscopic growth by use of linear interpolation w.r.t. mass 
+       !  fractions of each internally mixed component for each mode (kcomp).
+       !
```
Comment (gold2718) [inline physics/physpkg.F90]: I realize `AEROCOM` is not expected to work in this PR but if you want to include the code below, can you at least define the variables it uses (also inside of `#ifdef AEROOM`)?

**Review by gold2718 — CHANGES_REQUESTED** [review]
Questions and suggestions.

File: physics/cam_diagnostics.F90 (hunk 1 above)
Comment (mvertens) [reply physics/cam_diagnostics.F90]: Done.

File: physics/cam_diagnostics.F90 (hunk 2 above)
Comment (mvertens) [reply physics/cam_diagnostics.F90]: Changed it to indx.

File: physics/cam_diagnostics.F90 (hunk 3 above)
Comment (mvertens) [reply physics/cam_diagnostics.F90]: Done.

File: physics/cam_diagnostics.F90 (hunk 5 above)
Comment (mvertens) [reply physics/cam_diagnostics.F90]: Made everything even more simple. Please take a look.

File: physics/cam_diagnostics.F90 (hunk 8 above)
Comment (mvertens) [reply physics/cam_diagnostics.F90]: I'm simply going to remove them.

Comment (mvertens) [reply physics/cam_diagnostics.F90]: I'm been removing these type of comments as I go. It makes no sense at this point to keep them in.

File: physics/physpkg.F90 (hunk 10 above)
Comment (mvertens) [reply physics/physpkg.F90]: Because its totally different. And I wanted to have all the oslo_aero code to have a prefix of oslo_aero to eventually think of putting this in another model rather than having a name which matches cam.

File: physics/physpkg.F90 (hunk 11 above)
Comment (mvertens) [reply physics/physpkg.F90:1410]: Because its totally different. And I wanted to have all the oslo_aero code to have a prefix of oslo_aero to eventually think of putting this in another model rather than having a name which matches cam.

File: physics/physpkg.F90 (hunk 12 above)
Comment (mvertens) [reply physics/physpkg.F90]: Good point. I've actually removed the AEROCOM stuff from physpkg - since it really looks like it was not doing anything. We can go back and revisit this when we actually turn on AEROCOM.

**Review by gold2718 — APPROVED** [review]
This should be okay for now. Hopefully, we can lower the number of OSLO_AERO specific code changes as we refactor the Oslo Aero code.
